version: "2"
rules:
  - base: template
    upstream: ublue-os:template
    mergeMethod: hardreset
  - base: live
    upstream: template
  - base: dev
    upstream: live
label: ":arrow_heading_down: pull"
conflictLabel: "merge-conflict"