version: "1"
rules:
  - base: template
    upstream: ublue-os:template
    mergeMethod: hardreset
  - base: live
    upstream: template
label: ":arrow_heading_down: pull"
conflictLabel: "merge-conflict"
