# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# ^^^ Above line sets up validation in supported editors ^^^

name: silverflow-nvidia
description: My personal OS image (based on silverblue-nvidia from uBlue OS)
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: "40"

modules:
  - from-file: module-recipe/files.yml
  - from-file: module-recipe/scripts.yml
  - from-file: module-recipe/akmods.yml
  - from-file: module-recipe/rpm-ostree.yml
  - from-file: module-recipe/yafti.yml
  - from-file: module-recipe/default-flatpaks.yml
  - from-file: module-recipe/bling.yml
  - from-file: module-recipe/fonts.yml
  - type: brew
  - from-file: module-recipe/gnome-extensions.yml
  - from-file: module-recipe/gschema-overrides.yml
  - from-file: module-recipe/systemd.yml
  - type: signing
