modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      # Repo for Razer Hardware
      # - https://download.opensuse.org/repositories/hardware:/razer/Fedora_%OS_VERSION%/hardware:razer.repo
      # COPR for bibata-cursor-themes
      - https://copr.fedorainfracloud.org/coprs/peterwu/rendezvous/repo/fedora-%OS_VERSION%/peterwu-rendezvous.repo
    install:
      # - polychromatic
      # - openrazer-meta
      - bibata-cursor-themes
      - adw-gtk3-theme
    remove:
      - firefox
      - firefox-langpacks
      - gnome-software
      - gnome-software-rpm-ostree
      - gnome-tour

  - type: bling
    install:
      - fonts
      - dconf-update-service

  - type: systemd
    system:
      disabled:
        - flatpak-system-update.timer
        - rpm-ostreed-automatic.timer
    user:
      disabled:
        - flatpak-user-update.timer

  - type: yafti

  - type: script
    scripts:
      # - openrazer.sh
      - cleanup.sh
      - signing.sh
