modules:
  - type: files
    files:
      - usr: /usr

  - type: rpm-ostree
    repos:
      # COPR for bibata-cursor-themes
      - https://copr.fedorainfracloud.org/coprs/peterwu/rendezvous/repo/fedora-%OS_VERSION%/peterwu-rendezvous.repo
      # VSCode repository from bluefin
      - https://raw.githubusercontent.com/ublue-os/bluefin/main/dx/etc/yum.repos.d/vscode.repo
    install:
      # No builds for F39
      # - bibata-cursor-themes
      - adw-gtk3-theme
      - code
    remove:
      - firefox
      - firefox-langpacks
      - gnome-software
      - gnome-software-rpm-ostree
      - gnome-tour
      - gnome-terminal
      - gnome-terminal-nautilus

  - type: bling
    install:
      - fonts
      - dconf-update-service

  - type: systemd
    system:
      disabled:
        - flatpak-system-update.timer
        - rpm-ostreed-automatic.timer
    user:
      disabled:
        - flatpak-user-update.timer

  - type: yafti

  - type: script
    scripts:
      - cleanup.sh
      - signing.sh
