# image will be published to ghcr.io/<user>/<name>
name: silverflow
description: This is my personal OS image (based on silverblue-nvidia from uBlue OS)

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 38

modules:
  - type: files
    files:
      - usr:
          /usr
          # copy static configurations
          #
          # copies config/files/usr into your image's /usr
          #
          # configuration you wish to end up in /etc/ on the booted system
          # should be added into /usr/etc/ as that is the proper "distro"
          # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos: # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      # - micro
      # - starship
    remove:
      - firefox
      - firefox-langpacks
      - gnome-software 
      - gnome-software-rpm-ostree
      - gnome-tour

  - type: bling
    install:
      - fonts
      # - justfiles
      # - nix-installer # shell shortcuts for determinate system's nix installers
      - dconf-update-service # a service unit that updates the dconf db on boot

  # - type: yafti
  #   custom-flatpaks:
  #   - Celluloid: io.github.celluloid_player.Celluloid
  #   - Krita: org.kde.krita

  - type: systemd
    system:
      disabled:
        - flatpak-system-update.timer
        - rpm-ostreed-automatic.timer
    user:
      disabled:
        - flatpak-user-update.timer

  - type: script
    scripts:
      - signing.sh
