name: silverflow-nvidia
description: My personal OS image (based on silverblue-nvidia from uBlue OS)
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 39
is_latest_version: true
is_stable_version: false

modules:
  - from-file: config_modules/files.yml
  - from-file: config_modules/rpm-ostree.yml
  - from-file: config_modules/bling.yml

  - type: yafti

  - from-file: config_modules/systemd.yml
  - from-file: config_modules/scripts.yml
