name: silverflow-nvidia
description: My personal OS image (based on silverblue-nvidia from uBlue OS)
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 38
is_latest_version: true
is_stable_version: true

modules:
  - from-file: common_modules/files.yml
  - from-file: common_modules/rpm-ostree.yml

  - type: rpm-ostree
    repos:
      # Repo for Razer Hardware
      - https://download.opensuse.org/repositories/hardware:/razer/Fedora_%OS_VERSION%/hardware:razer.repo
    install:
      - podman-docker
      - polychromatic
      - openrazer-meta
      - bibata-cursor-themes

  - from-file: common_modules/bling.yml
  - from-file: common_modules/fonts.yml

  - type: yafti

  - from-file: common_modules/systemd.yml
  - from-file: common_modules/scripts.yml

  - type: script
    scripts:
      - container-tools.sh
      - openrazer.sh
