name: silverflow-nvidia-gts
description: My personal OS image (based on silverblue-nvidia from uBlue OS)
base-image: ghcr.io/ublue-os/silverblue-nvidia
image-version: 38
is_latest_version: false
is_stable_version: true
is_gts_version: true

modules:
  - from-file: common_modules/akmods.yml
  - from-file: common_modules/files.yml
  - from-file: common_modules/rpm-ostree.yml
  - from-file: common_modules/default-flatpaks.yml
  - from-file: common_modules/yafti.yml
  - from-file: common_modules/fonts.yml
  - from-file: common_modules/bling.yml
  - from-file: common_modules/systemd.yml
  - from-file: common_modules/image-cleaner.yml
  - from-file: common_modules/scripts.yml
