title: Welcome to uBlue
properties:
  mode: "run-on-change"
screens:
  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to SilverFlow"
      icon: "/path/to/icon"
      description: |
        Default system apps are installing in the background, but it is safe to use your computer in the meantime.
  applications:
    source: yafti.screen.package
    values:
      title: Application Installer
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      package_manager_defaults:
        system: true
      groups:
        DefaultPlus Apps:
          description: Additional default applications for all desktop environments.
          default: false
          packages:
            - Fedora Media Writer: org.fedoraproject.MediaWriter
            - Mozilla Firefox: org.mozilla.firefox
            - FreeFileSync: org.freefilesync.FreeFileSync
            - Proton VPN (Unofficial!): com.protonvpn.www
        Web Browsers:
          description: Additional browsers to complement or replace Firefox.
          default: false
          packages:
            - Brave: com.brave.Browser
            - GNOME Web: org.gnome.Epiphany
            - Google Chrome: com.google.Chrome
            - Microsoft Edge: com.microsoft.Edge
            - Opera: com.opera.Opera
        Gaming:
          description: "Rock and Stone!"
          default: false
          packages:
            - Bottles: com.usebottles.bottles
            - Discord: com.discordapp.Discord
            - ArmCord (Custom Discord Client): xyz.armcord.ArmCord
            - WebCord (Custom Discord Client): io.github.spacingbat3.webcord
            - Heroic Games Launcher: com.heroicgameslauncher.hgl
            - Steam: com.valvesoftware.Steam
            - Lutris: net.lutris.Lutris
        Entertainment:
          description: Relax and take a break.
          default: false
          packages:
            - Spotify: com.spotify.Client
        Coding:
          description: You gotta do what you gotta do.
          default: false
          packages:
            - VSCode: com.visualstudio.code
            - VSCodium: com.vscodium.codium
            - BlackBox (Terminal): com.raggesilver.BlackBox
        Office:
          description: Boost your productivity.
          default: false
          packages:
            - LibreOffice: org.libreoffice.LibreOffice
            - OnlyOffice: org.onlyoffice.desktopeditors
            - Obsidian: md.obsidian.Obsidian
            - Slack: com.slack.Slack
        Custom:
          description: Other uncategorized applications.
          default: false
          packages:
            - ZapZap: com.rtosta.zapzap
            - Caprine: com.sindresorhus.Caprine
            - Materialgram: io.github.kukuruzka165.materialgram
            - Upscayl: org.upscayl.Upscayl
  configure-silveflow:
    source: yafti.screen.package
    values:
      title: Additional SilverFlow configs
      show_terminal: true
      package_manager: yafti.plugin.run
      groups:         
        Hide GRUB:
          description: Hides GRUB text output on boot.
          default: false
          packages:
          - Hide GRUB: pkexec ujust configure-grub hide
  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      icon: "/path/to/icon"
      links:
        - "Website":
            run: /usr/bin/xdg-open https://universal-blue.org/
        - "Join the Discord Community":
            run: /usr/bin/xdg-open https://discord.gg/XjG48C7VHx
      description: |
        Thanks for trying SilverFlow, I hope you enjoy it!
