title: Welcome to uBlue
properties:
  mode: "run-on-change"
screens:

  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to SilverFlow"
      icon: "/path/to/icon"
      description: |
        Default system apps are installing in the background, but it is safe to use your computer in the meantime.
        
  applications:
    source: yafti.screen.package
    values:
      title: Application Installer
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      package_manager_defaults:
        system: false
        user: true
      groups:
        Utilities and System Tools:
          description: Essential tools for your system.
          default: false
          packages:
            - DejaDup: org.gnome.DejaDup
            - FreeFileSync: org.freefilesync.FreeFileSync
            - Metadata Cleaner: fr.romainvigier.MetadataCleaner
            - Mission Center: io.missioncenter.MissionCenter
            - Impression: io.gitlab.adhami3310.Impression
            - Obfuscate: com.belmoussaoui.Obfuscate.Locale
            - Pika Backup: org.gnome.World.PikaBackup
            - PinApp: io.github.fabrialberio.pinapp
            - Pods: com.github.marhkb.Pods
            - qBittorrent: org.qbittorrent.qBittorrent
            - Resources: net.nokyan.Resources
            - Upscaler: io.gitlab.theevilskeleton.Upscaler
            - VLC: org.videolan.VLC
            - Weather: io.github.amit9838.weather
        Browsers:
          description: Additional browsers to complement Brave
          default: false
          packages:
            - Chromium: org.chromium.Chromium
            - Firefox: org.mozilla.firefox
            - GNOME Web: org.gnome.Epiphany
            - Google Chrome: com.google.Chrome
            - Librewolf: io.gitlab.librewolf-community
            - Microsoft Edge: com.microsoft.Edge
            - Opera: com.opera.Opera
            - Vivaldi: com.vivaldi.Vivaldi
        Gaming:
          description: "Rock and Stone!"
          default: false
          packages:
            - BoilR: io.github.philipk.boilr
            - Bottles: com.usebottles.bottles
            - Cartridges (Universal Game Launcher): hu.kramo.Cartridges
            - Chiaki (PlayStation Remote Play): re.chiaki.Chiaki
            - DOSBox Staging: io.github.dosbox-staging
            - GeForce NOW Electron: io.github.hmlendea.geforcenow-electron
            - Greenlight: io.github.unknownskl.greenlight
            - Heroic Games Launcher (GOG &amp; Epic): com.heroicgameslauncher.hgl
            - itch: io.itch.itch
            - ludusavi (Game Save Backup): com.github.mtkennerly.ludusavi
            - Minecraft (Prism Launcher): org.prismlauncher.PrismLauncher
            - Minecraft Bedrock Launcher: io.mrarm.mcpelauncher
            - Moonlight: com.moonlight_stream.Moonlight
            - Mumble: info.mumble.Mumble
            - OpenMW: org.openmw.OpenMW
            - osu: sh.ppy.osu
            - Parsec: com.parsecgaming.parsec
            - Space Cadet Pinball: com.github.k4zmu2a.spacecadetpinball
            - Sonic Robo Blast 2: org.srb2.SRB2
            - Sonic Robo Blast 2 Kart: org.srb2.SRB2Kart
            - Steam Link: com.valvesoftware.SteamLink
            - SuperTux: org.supertuxproject.SuperTux
            - SuperTuxKart: net.supertuxkart.SuperTuxKart
            - TeamSpeak: com.teamspeak.TeamSpeak
            - XIV Launcher (Final Fantasy XIV): dev.goats.xivlauncher
        Music:
          description: "Rock and Roll!"
          default: false
          packages:
            - Cider (Apple Music Client): sh.cider.Cider
            - Spotify: com.spotify.Client
            - Strawberry Music Player: org.strawberrymusicplayer.strawberry
            - Tidal-hifi: com.mastermindzh.tidal-hifi
        Coding:
          description: You gotta do what you gotta do.
          default: false
          packages:
            - VSCode: com.visualstudio.code
            - VSCodium: com.vscodium.codium
            - BlackBox (Terminal): com.raggesilver.BlackBox
            - Lapce: dev.lapce.lapce
        Office and Productivity:
          description: Bow to Capitalism
          default: false
          packages:
            - Ardour: org.ardour.Ardour
            - Blender: org.blender.Blender
            - darktable: org.darktable.Darktable
            - GIMP: org.gimp.GIMP
            - Inkscape: org.inkscape.Inkscape
            - Joplin: net.cozic.joplin_desktop
            - Kdenlive: org.kde.kdenlive
            - Krita: org.kde.krita
            - LibreOffice: org.libreoffice.LibreOffice
            - Obsidian: md.obsidian.Obsidian
            - OnlyOffice: org.onlyoffice.desktopeditors
            - Planify: io.github.alainm23.planify
            - Slack: com.slack.Slack
            - Standard Notes: org.standardnotes.standardnotes
            - Tenacity: org.tenacityaudio.Tenacity
            - Thunderbird Email: org.mozilla.Thunderbird
        Social:
          description: Stay connected.
          default: false
          packages:
            - Caprine: com.sindresorhus.Caprine
            - Discord: com.discordapp.Discord
            - Element: im.riot.Riot
            - Flare: de.schmidhuberj.Flare
            - Signal: org.signal.Signal
            - Telegram: org.telegram.desktop
            - Vesktop (Custom Discord Client): dev.vencord.Vesktop

  can-we-harden-your-kargs:
    source: yafti.screen.consent
    values:
      title: Kernel hardening
      description: |
        This step will enable additional kernel hardening. If you encounter any issues, execute the following command in a terminal: `ujust set-kargs-hardening delete`
      actions:
        - run: pkexec ujust set-kargs-hardening append

  can-we-hide-grub:
    source: yafti.screen.consent
    values:
      title: Hide GRUB
      description: |
        This step will hide GRUB from the boot process. If you want to access GRUB, hold down the ESC key during boot.
      actions:
        - run: pkexec ujust configure-grub hide

  can-we-append-kargs-nvidia:
    source: yafti.screen.consent
    values:
      title: NVIDIA Kernel Parameters
      description: |
        This step will append needed kernel parameters for NVIDIA drivers. If you have an NVIDIA GPU, you should run this. 
      actions:
        - run: pkexec ujust configure-nvidia kargs

  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      icon: "/path/to/icon"
      links:
        - "Website":
            run: /usr/bin/xdg-open https://universal-blue.org/
        - "Join the Discord Community":
            run: /usr/bin/xdg-open https://discord.gg/XjG48C7VHx
      description: |
        Thanks for trying SilverFlow, I hope you enjoy it!
