title: Welcome to uBlue
properties:
  mode: "run-on-change"
screens:

  first-screen:
    source: yafti.screen.title
    values:
      title: "Welcome to SilverFlow"
      icon: "/path/to/icon"
      description: |
        Default system apps are installing in the background, but it is safe to use your computer in the meantime.
        
  applications:
    source: yafti.screen.package
    values:
      title: Application Installer
      show_terminal: true
      package_manager: yafti.plugin.flatpak
      package_manager_defaults:
        system: false
        user: true
      groups:
        DefaultPlus Apps:
          description: Additional default applications for all desktop environments.
          default: false
          packages:
            - Impression: io.gitlab.adhami3310.Impression
            - GNOME Web: org.gnome.Epiphany
            - FreeFileSync: org.freefilesync.FreeFileSync
            - Upscaler: io.gitlab.theevilskeleton.Upscaler
            - Weather: io.github.amit9838.weather
        Browsers:
          description: "Surf the web."
          default: false
          packages:
            - Firefox: org.mozilla.firefox
            - Chromium: org.chromium.Chromium
            - Vivaldi: com.vivaldi.Vivaldi
            - Edge: com.microsoft.Edge
            - Opera: com.opera.Opera
            - Librewolf: io.gitlab.librewolf-community
        Gaming:
          description: "Rock and Stone!"
          default: false
          packages:
            - Bottles: com.usebottles.bottles
            - Heroic Games Launcher: com.heroicgameslauncher.hgl
            - Steam: com.valvesoftware.Steam
            - Lutris: net.lutris.Lutris
            - Steam: com.valvesoftware.Steam
            - ProtonPlus (Steam Proton Manager): com.vysp3r.ProtonPlus
            - PCSX2 (PS2 Emulator): net.pcsx2.PCSX2
            - Space Cadet Pinball: com.github.k4zmu2a.spacecadetpinball
            - Cartridges (Universal Game Launcher): hu.kramo.Cartridges
        Entertainment:
          description: Relax and take a break.
          default: false
          packages:
            - Spotify: com.spotify.Client
            - FreeTube: io.freetubeapp.FreeTube
        Coding:
          description: You gotta do what you gotta do.
          default: false
          packages:
            - VSCode: com.visualstudio.code
            - VSCodium: com.vscodium.codium
            - BlackBox (Terminal): com.raggesilver.BlackBox
            - Lapce: dev.lapce.lapce
        Office:
          description: Boost your productivity.
          default: false
          packages:
            - LibreOffice: org.libreoffice.LibreOffice
            - OnlyOffice: org.onlyoffice.desktopeditors
            - Obsidian: md.obsidian.Obsidian
            - Slack: com.slack.Slack
        Privacy:
          description: Keep your data safe.
          default: false
          packages:
            - Obfuscate: com.belmoussaoui.Obfuscate.Locale
            - Metadata Cleaner: fr.romainvigier.MetadataCleaner
        Social:
          description: Stay connected.
          default: false
          packages:
            - Discord: com.discordapp.Discord
            - Vesktop (Custom Discord Client): dev.vencord.Vesktop
            - Telegram: org.telegram.desktop
            - Caprine: com.sindresorhus.Caprine
            - Element: im.riot.Riot
            - Signal: org.signal.Signal
            - Flare: de.schmidhuberj.Flare

  can-we-harden-your-kargs:
    source: yafti.screen.consent
    values:
      title: Kernel hardening
      description: |
        This step will enable additional kernel hardening. If you encounter any issues, execute the following command in a terminal: `ujust set-kargs-hardening delete`
      actions:
        - run: pkexec ujust set-kargs-hardening append

  can-we-hide-grub:
    source: yafti.screen.consent
    values:
      title: Hide GRUB
      description: |
        This step will hide GRUB from the boot process. If you want to access GRUB, hold down the ESC key during boot.
      actions:
        - run: pkexec ujust configure-grub hide

  can-we-append-kargs-nvidia:
    source: yafti.screen.consent
    values:
      title: NVIDIA Kernel Parameters
      description: |
        This step will append needed kernel parameters for NVIDIA drivers. If you have an NVIDIA GPU, you should run this. 
      actions:
        - run: pkexec ujust configure-nvidia kargs

  final-screen:
    source: yafti.screen.title
    values:
      title: "All done!"
      icon: "/path/to/icon"
      links:
        - "Website":
            run: /usr/bin/xdg-open https://universal-blue.org/
        - "Join the Discord Community":
            run: /usr/bin/xdg-open https://discord.gg/XjG48C7VHx
      description: |
        Thanks for trying SilverFlow, I hope you enjoy it!
