type: default-flatpaks
system:
  repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
  repo-name: flathub
  repo-title: "Flathub (system-wide)"
  install:
    - org.gnome.Calculator
    - org.gnome.Calendar
    - org.gnome.Characters
    - org.gnome.Evince
    - org.gnome.Logs
    - org.gnome.Loupe
    - org.gnome.NautilusPreviewer
    - org.gnome.SimpleScan
    - org.gnome.TextEditor
    - org.gnome.World.PikaBackup
    - org.gnome.baobab
    - org.gnome.clocks
    - com.github.rafostar.Clapper
    - com.github.tchx84.Flatseal
    - com.mattjakeman.ExtensionManager
    - com.raggesilver.BlackBox
    - io.missioncenter.MissionCenter
    - com.github.marhkb.Pods
