type: rpm-ostree
repos:
  # COPR for bibata-cursor-themes
  - https://copr.fedorainfracloud.org/coprs/peterwu/rendezvous/repo/fedora-%OS_VERSION%/peterwu-rendezvous.repo
  # VSCode repository from bluefin
  - https://raw.githubusercontent.com/ublue-os/bluefin/main/dx/etc/yum.repos.d/vscode.repo
install:
  - adw-gtk3-theme
  - code
remove:
  - firefox
  - firefox-langpacks
  - gnome-software
  - gnome-software-rpm-ostree
  - gnome-tour
  - gnome-terminal
  - gnome-terminal-nautilus
  - gnome-classic-session
