type: rpm-ostree
repos:
  # VSCode repository from bluefin
  - https://raw.githubusercontent.com/ublue-os/bluefin/main/dx/etc/yum.repos.d/vscode.repo
install:
  - gnome-console
  - code
remove:
  - gnome-tweaks
  - gnome-software
  - gnome-software-rpm-ostree
  - gnome-tour
  - gnome-terminal
  - gnome-terminal-nautilus
  - gnome-classic-session
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-places-menu
  - gnome-shell-extension-background-logo
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-window-list
  - gnome-system-monitor
  - toolbox
  - yelp
