type: rpm-ostree
repos:
  # Repo for system76-scheduler
  - https://copr.fedorainfracloud.org/coprs/kylegospo/system76-scheduler/repo/fedora-%OS_VERSION%/kylegospo-system76-scheduler-fedora-%OS_VERSION%.repo
  # Repo for system76
  - https://copr.fedorainfracloud.org/coprs/szydell/system76/repo/fedora-%OS_VERSION%/szydell-system76-fedora-%OS_VERSION%.repo
  # VSCode repository from bluefin
  - https://raw.githubusercontent.com/ublue-os/bluefin/main/dx/etc/yum.repos.d/vscode.repo
  # Repo for Razer Hardware
  - https://download.opensuse.org/repositories/hardware:/razer/Fedora_%OS_VERSION%/hardware:razer.repo
install:
  - gnome-console
  - adw-gtk3-theme
  - code
  - polychromatic
  - openrazer-meta
  - system76-scheduler
  - system76-power
  - gnome-shell-extension-system76-scheduler
remove:
  - firefox
  - firefox-langpacks
  - gnome-software
  - gnome-software-rpm-ostree
  - gnome-tour
  - gnome-terminal
  - gnome-terminal-nautilus
  - gnome-classic-session
  - gnome-shell-extension-apps-menu
  - gnome-shell-extension-places-menu
  - gnome-shell-extension-background-logo
  - gnome-shell-extension-launch-new-instance
  - gnome-shell-extension-window-list
