type: script
scripts:
  - brave-browser.sh
  - power-scheduler.sh
  - systemwide-themes.sh
snippets:
  - "rpm-ostree install https://proton.me/download/mail/linux/ProtonMail-desktop-beta.rpm"
  - "chmod 440 /usr/etc/sudoers.d/timeout"
