# This workflow builds 'live' branch of the repository daily at 16:00 UTC (30 min delay after 'ublue-os/nvidia' builds)

name: bluebuild
on: 
  schedule:
    - cron: "00 16 * * *"
  push:
    branches:
      - live
      - blue-build
    paths-ignore: 
      - "**.md"
  pull_request:
  workflow_dispatch:

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - silverflow-nvidia-39.yml
          - silverflow-nvidia-gts.yml
                  
    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@main
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}